### ISSUE TITLE
Issues when running on Linux(wine)

### ISSUE THREAD

**Issue by KatouMegumi-osu** [Milkitic/KeyASIO.Net#7]
HI. I was trying to use this software on wine, to see if it would work better than current community wine solutions.

Even though we have our own methods for low latency audio playback (like reverting winepulse and patching it, using pipewire), I wanted to potentially explore this software as well. Unfortunately, the software is having issues playing audio at all. Sometimes if you fiddle enough, it would play something. But most of the time it's only the beatmap mp3 and not hitsounds.

Testing environment:
Arch Linux (but could use any distribution, I think.)
Wine staging 7.14 (I am personally faulting this, because staging has file access speed issues)
64 bit prefix, but only 32 bit version of the program launches.
wineasio installed on the prefix
$ winetricks -q -f dotnet48

log (if needed: https://gist.github.com/KatouMegumi-osu/17d92d00b88a3ff3a2aefb44e13d8de5

**Comment by Milkitic** [comment]
Hi. I'm not sure whether this program can run on wine since it was totally not tested. But I may provide some help to resolve the error according to your log:
```
Error while resampling audio file Z:\home\megumi\Downloads\osu\Skins\funniskin2\
soft-hitnormal.wav: Unable to cast COM object of type 'NAudio.Dmo.ResamplerMedia
ComObject' to interface type 'NAudio.Dmo.IWMResamplerProps'. This operation fail
ed because the QueryInterface call on the COM component for the interface with I
ID '{E7E9984F-F09F-4DA4-903F-6E2E0EFE56B5}' failed due to the following error: 0
x80004002 (E_NOINTERFACE).
```

Each audio should be resampled before mixing them if the SampleRate doesn't match. For hitsounds we currently use `MediaFoundationResampler` by NAudio to work. NAudio is an audio framework only for windows and used in this project. It throws error because some components are missing, you can refer to https://docs.microsoft.com/en-us/windows/win32/api/wmcodecdsp/, and try to install related components to resolve.

**Comment by Milkitic** [comment]
osu in linux seems to be able run in a low latency state with native audio experience, so this software has little effect (even negative effect) on Linux.
An example instruction here: https://osu.ppy.sh/community/forums/topics/1248084
